export const ERROR_CODES = {
  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  TOKEN_INVALID: "TOKEN_INVALID",
  ROLE_NOT_FOUND: "ROLE_NOT_FOUND",
  INSUFFICIENT_ROLE: "INSUFFICIENT_ROLE",
  LOAN_NOT_FOUND: "LOAN_NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  ROUTE_NOT_FOUND: "ROUTE_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  CONFIG_MISSING: "CONFIG_MISSING"
} as const;